COUNTRIES_DATABASE = {
    # Format: "id": ["Name", "Short Name", "Abbreviation", "Confederation", "ISO Code", "Level", "National Team Rating", "Flag Code"]
    "42": ["England", "England", "ENG", "UEFA", "GB-ENG", "1", "85", "ENG"],
    "45": ["Spain", "España", "ESP", "UEFA", "ESP", "1", "86", "ESP"],
    "46": ["France", "France", "FRA", "UEFA", "FRA", "1", "87", "FRA"],
    "47": ["Germany", "Deutschland", "GER", "UEFA", "DEU", "1", "85", "GER"],
    "48": ["Italy", "Italia", "ITA", "UEFA", "ITA", "1", "84", "ITA"],
    "49": ["Portugal", "Portugal", "POR", "UEFA", "PRT", "1", "85", "POR"],
    "50": ["Netherlands", "Nederland", "NED", "UEFA", "NLD", "1", "84", "NED"],
    "51": ["Belgium", "België", "BEL", "UEFA", "BEL", "1", "84", "BEL"],
    "52": ["Argentina", "Argentina", "ARG", "CONMEBOL", "ARG", "1", "86", "ARG"],
    "53": ["Brazil", "Brasil", "BRA", "CONMEBOL", "BRA", "1", "85", "BRA"],
    "54": ["Uruguay", "Uruguay", "URU", "CONMEBOL", "URY", "1", "83", "URU"],
    "55": ["Colombia", "Colombia", "COL", "CONMEBOL", "COL", "2", "80", "COL"],
    "56": ["Chile", "Chile", "CHI", "CONMEBOL", "CHL", "2", "78", "CHI"],
    "57": ["Mexico", "México", "MEX", "CONCACAF", "MEX", "2", "80", "MEX"],
    "58": ["United States", "USA", "USA", "CONCACAF", "USA", "2", "81", "USA"],
    "59": ["Croatia", "Hrvatska", "CRO", "UEFA", "HRV", "1", "83", "CRO"],
    "60": ["Denmark", "Danmark", "DEN", "UEFA", "DNK", "1", "82", "DEN"],
    "61": ["Poland", "Polska", "POL", "UEFA", "POL", "2", "81", "POL"],
    "62": ["Switzerland", "Schweiz", "SUI", "UEFA", "CHE", "2", "80", "SUI"],
    "63": ["Morocco", "المغرب", "MAR", "CAF", "MAR", "2", "81", "MAR"],
    "64": ["Senegal", "Sénégal", "SEN", "CAF", "SEN", "2", "80", "SEN"],
    "65": ["Japan", "日本", "JPN", "AFC", "JPN", "2", "79", "JPN"],
    "66": ["South Korea", "대한민국", "KOR", "AFC", "KOR", "2", "78", "KOR"],
    "67": ["Australia", "Australia", "AUS", "AFC", "AUS", "2", "77", "AUS"],
    "68": ["Saudi Arabia", "السعودية", "KSA", "AFC", "SAU", "2", "76", "KSA"],
    "69": ["Iran", "ایران", "IRN", "AFC", "IRN", "2", "77", "IRN"],
    "70": ["Egypt", "مصر", "EGY", "CAF", "EGY", "2", "78", "EGY"],
    "71": ["Nigeria", "Nigeria", "NGA", "CAF", "NGA", "2", "78", "NGA"],
    "72": ["Ghana", "Ghana", "GHA", "CAF", "GHA", "2", "77", "GHA"],
    "73": ["Algeria", "الجزائر", "ALG", "CAF", "DZA", "2", "77", "ALG"],
    "74": ["Tunisia", "تونس", "TUN", "CAF", "TUN", "2", "76", "TUN"],
    "75": ["Sweden", "Sverige", "SWE", "UEFA", "SWE", "2", "79", "SWE"],
    "76": ["Norway", "Norge", "NOR", "UEFA", "NOR", "2", "78", "NOR"],
    "77": ["Austria", "Österreich", "AUT", "UEFA", "AUT", "2", "78", "AUT"],
    "78": ["Czech Republic", "Česko", "CZE", "UEFA", "CZE", "2", "77", "CZE"],
    "79": ["Hungary", "Magyarország", "HUN", "UEFA", "HUN", "2", "77", "HUN"],
    "80": ["Turkey", "Türkiye", "TUR", "UEFA", "TUR", "2", "77", "TUR"],
    "81": ["Greece", "Ελλάδα", "GRE", "UEFA", "GRC", "2", "76", "GRE"],
    "82": ["Serbia", "Србија", "SRB", "UEFA", "SRB", "2", "78", "SRB"],
    "83": ["Ukraine", "Україна", "UKR", "UEFA", "UKR", "2", "77", "UKR"],
    "84": ["Romania", "România", "ROU", "UEFA", "ROU", "2", "76", "ROU"],
    "85": ["Wales", "Cymru", "WAL", "UEFA", "GB-WLS", "2", "76", "WAL"],
    "86": ["Scotland", "Scotland", "SCO", "UEFA", "GB-SCT", "2", "76", "SCO"],
    "87": ["Ireland", "Éire", "IRL", "UEFA", "IRL", "2", "75", "IRL"],
    "88": ["Northern Ireland", "North. Ireland", "NIR", "UEFA", "GB-NIR", "2", "74", "NIR"],
    "89": ["Iceland", "Ísland", "ISL", "UEFA", "ISL", "2", "74", "ISL"],
    "90": ["Finland", "Suomi", "FIN", "UEFA", "FIN", "2", "75", "FIN"],
    "91": ["Peru", "Perú", "PER", "CONMEBOL", "PER", "2", "75", "PER"],
    "92": ["Ecuador", "Ecuador", "ECU", "CONMEBOL", "ECU", "2", "76", "ECU"],
    "93": ["Paraguay", "Paraguay", "PAR", "CONMEBOL", "PRY", "2", "75", "PAR"],
    "94": ["Venezuela", "Venezuela", "VEN", "CONMEBOL", "VEN", "2", "74", "VEN"],
    "95": ["Bolivia", "Bolivia", "BOL", "CONMEBOL", "BOL", "3", "72", "BOL"],
    "96": ["Canada", "Canada", "CAN", "CONCACAF", "CAN", "2", "76", "CAN"],
    "97": ["Costa Rica", "Costa Rica", "CRC", "CONCACAF", "CRI", "2", "75", "CRC"],
    "98": ["Jamaica", "Jamaica", "JAM", "CONCACAF", "JAM", "3", "72", "JAM"],
    "99": ["Panama", "Panamá", "PAN", "CONCACAF", "PAN", "3", "71", "PAN"],
    "100": ["Honduras", "Honduras", "HON", "CONCACAF", "HND", "3", "71", "HON"],
    "149": ["Afghanistan", "Afghanistan", "AFG", "AFC", "AFG", "4", "65", "AFG"]
} 